export interface Country {
    name: string;
    code: string;
    flag: string;
}

export const COUNTRIES: Country[] = [
    { name: 'India', code: '+91', flag: 'IN' },
    { name: 'United States', code: '+1', flag: 'US' },
    { name: 'United Kingdom', code: '+44', flag: 'GB' },
    { name: 'Canada', code: '+1', flag: 'CA' },
    { name: 'Australia', code: '+61', flag: 'AU' },
    { name: 'Germany', code: '+49', flag: 'DE' },
    { name: 'France', code: '+33', flag: 'FR' },
    { name: 'Japan', code: '+81', flag: 'JP' },
    { name: 'China', code: '+86', flag: 'CN' },
    { name: 'Brazil', code: '+55', flag: 'BR' },
    { name: 'South Africa', code: '+27', flag: 'ZA' },
    { name: 'United Arab Emirates', code: '+971', flag: 'AE' },
    { name: 'Singapore', code: '+65', flag: 'SG' },
    { name: 'Netherlands', code: '+31', flag: 'NL' },
    { name: 'Spain', code: '+34', flag: 'ES' },
    { name: 'Italy', code: '+39', flag: 'IT' },
    { name: 'Russia', code: '+7', flag: 'RU' },
    { name: 'Mexico', code: '+52', flag: 'MX' },
    { name: 'Nigeria', code: '+234', flag: 'NG' },
    { name: 'Saudi Arabia', code: '+966', flag: 'SA' },
    { name: 'Argentina', code: '+54', flag: 'AR' },
    { name: 'Turkey', code: '+90', flag: 'TR' },
    { name: 'Indonesia', code: '+62', flag: 'ID' },
    { name: 'Switzerland', code: '+41', flag: 'CH' },
    { name: 'Sweden', code: '+46', flag: 'SE' },
    { name: 'Norway', code: '+47', flag: 'NO' },
    { name: 'Denmark', code: '+45', flag: 'DK' },
    { name: 'Finland', code: '+358', flag: 'FI' },
    { name: 'New Zealand', code: '+64', flag: 'NZ' },
    { name: 'Ireland', code: '+353', flag: 'IE' },
    { name: 'Portugal', code: '+351', flag: 'PT' },
    { name: 'Belgium', code: '+32', flag: 'BE' },
    { name: 'Austria', code: '+43', flag: 'AT' },
    { name: 'Greece', code: '+30', flag: 'GR' },
    { name: 'Egypt', code: '+20', flag: 'EG' },
    { name: 'Israel', code: '+972', flag: 'IL' },
    { name: 'Malaysia', code: '+60', flag: 'MY' },
    { name: 'Thailand', code: '+66', flag: 'TH' },
    { name: 'Vietnam', code: '+84', flag: 'VN' },
    { name: 'Philippines', code: '+63', flag: 'PH' },
    { name: 'Ukraine', code: '+380', flag: 'UA' },
    { name: 'Poland', code: '+48', flag: 'PL' },
    { name: 'Czech Republic', code: '+420', flag: 'CZ' },
    { name: 'Hungary', code: '+36', flag: 'HU' },
    { name: 'Romania', code: '+40', flag: 'RO' },
    { name: 'Colombia', code: '+57', flag: 'CO' },
    { name: 'Chile', code: '+56', flag: 'CL' },
    { name: 'Peru', code: '+51', flag: 'PE' },
    { name: 'Pakistan', code: '+92', flag: 'PK' },
    { name: 'Bangladesh', code: '+880', flag: 'BD' },
    { name: 'Iran', code: '+98', flag: 'IR' },
    { name: 'Iraq', code: '+964', flag: 'IQ' },
    { name: 'Kenya', code: '+254', flag: 'KE' },
    { name: 'Morocco', code: '+212', flag: 'MA' },
    { name: 'Ghana', code: '+233', flag: 'GH' },
    { name: 'Algeria', code: '+213', flag: 'DZ' },
    { name: 'Ethiopia', code: '+251', flag: 'ET' },
    { name: 'Tanzania', code: '+255', flag: 'TZ' },
    { name: 'Uganda', code: '+256', flag: 'UG' },
    { name: 'Sudan', code: '+249', flag: 'SD' },
    { name: 'Nepal', code: '+977', flag: 'NP' },
    { name: 'Sri Lanka', code: '+94', flag: 'LK' },
    { name: 'Jordan', code: '+962', flag: 'JO' },
    { name: 'Lebanon', code: '+961', flag: 'LB' },
    { name: 'Kuwait', code: '+965', flag: 'KW' },
    { name: 'Oman', code: '+968', flag: 'OM' },
    { name: 'Qatar', code: '+974', flag: 'QA' },
    { name: 'Bahrain', code: '+973', flag: 'BH' },
    { name: 'Cote d-Ivoire', code: '+225', flag: 'CI' },
    { name: 'Cameroon', code: '+237', flag: 'CM' },
    { name: 'Senegal', code: '+221', flag: 'SN' },
    { name: 'Guatemala', code: '+502', flag: 'GT' },
    { name: 'Ecuador', code: '+593', flag: 'EC' },
    { name: 'Bolivia', code: '+591', flag: 'BO' },
    { name: 'Uruguay', code: '+598', flag: 'UY' },
    { name: 'Paraguay', code: '+595', flag: 'PY' },
    { name: 'Costa Rica', code: '+506', flag: 'CR' },
    { name: 'Panama', code: '+507', flag: 'PA' },
    { name: 'Dominican Republic', code: '+1-809', flag: 'DO' },
    { name: 'Croatia', code: '+385', flag: 'HR' },
    { name: 'Serbia', code: '+381', flag: 'RS' },
    { name: 'Bulgaria', code: '+359', flag: 'BG' },
    { name: 'Slovakia', code: '+421', flag: 'SK' },
    { name: 'Lithuania', code: '+370', flag: 'LT' },
    { name: 'Latvia', code: '+371', flag: 'LV' },
    { name: 'Estonia', code: '+372', flag: 'EE' },
    { name: 'Slovenia', code: '+386', flag: 'SI' },
    { name: 'Luxembourg', code: '+352', flag: 'LU' },
    { name: 'Iceland', code: '+354', flag: 'IS' },
    { name: 'Cyprus', code: '+357', flag: 'CY' },
    { name: 'Malta', code: '+356', flag: 'MT' }
];
