export const API_ENDPOINTS = {
    COUNTRIES: 'Country/GetAllCountries',
    CURRENCIES: 'CurrencyType/GetAllCurrencyTypes',
    APPOINTMENTS: 'Appointment/GetAll',
    HOME_BANNER: 'Home/GetBanner',
    PSYCHOLOGIST_LIST: 'Psychologist/GetAll',
    USER_PROFILE: 'User/GetProfile',
    WEBINAR_LIST: 'Zoom/getWebinarList?fetchFromDb=true',
    WEBINAR_REGISTER: 'Zoom/RegisterWebinarParticipant',
    USER_LOGIN: 'Authenticate/V2/Patient/Login',
    USER_REQUEST_PASSWORD_RESET: 'Authenticate/PatientRequestPasswordReset',
    USER_COMPLETE_PROFILE: 'Patient/V2/CompleteProfile',
    USER_SET_PASSWORD: 'Patient/V2/SetProfilePassword',
    SESSION_START: 'Session/Start',
    CHECKOUT: 'payment/create-checkout-session',
    VOUCHER_ADD: 'User/AddVoucher',
    ENTERPRISE_ADD: 'CorporateUser/AddEnterprise',
    ENTERPRISE_ADD_VOUCHER_DETAILS: 'CorporateUser/AddVoucherDetails',
    ENTERPRISE_ADD_VOUCHER_CODES: 'CorporateUser/AddVoucherCodesFromDetails',
    EDUCATION_ADD: 'CorporateUser/AddEducation',
    GET_PATIENT_PROFILE: 'PatientV2/GetPatientById',
    SAVE_PATIENT_PROFILE: 'PatientV2/SaveProfileDetails',
    COMMON_UPLOAD_FILE: 'Common/upload',
    GET_JOBS: 'Career/GetAllJobDetails',
    GET_JOB_BY_ID: 'Career/GetJobDetailsById',
    APPLY_JOB: 'Career/ApplyJob'
};
